name: Validate YAML

on:
  push:

jobs:
  build:
    name: Veriy valid YAML (Super-Linter)
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Run Linter
        uses: github/super-linter@v2.0.0
        env:
          VALIDATE_ALL_CODEBASE: false # Only lint changed files
          VALIDATE_ANSIBLE: false
